import award from '../assets/images/award.png'
import bg from '../assets/images/bg.jpg'
import bullet from '../assets/images/bullet.png'
import close from '../assets/images/close.png'
import copyright from '../assets/images/copyright.png'
import enemy1 from '../assets/images/enemy1.png'
import enemy2 from '../assets/images/enemy2.png'
import enemy3 from '../assets/images/enemy3.png'
import explode1 from '../assets/images/explode1.png'
import explode2 from '../assets/images/explode2.png'
import explode3 from '../assets/images/explode3.png'
import logo from '../assets/images/logo.jpg'
import mybullet from '../assets/images/mybullet.png'
import myexplode from '../assets/images/myexplode.png'
import myplane from '../assets/images/myplane.png'
import preloader from '../assets/images/preloader.gif'
import replaybutton from '../assets/images/replaybutton.png'
import share from '../assets/images/share.png'
import sharebutton from '../assets/images/sharebutton.png'
import startbutton from '../assets/images/startbutton.png'

export default {award,bg,bullet,close,copyright,enemy1,enemy2,enemy3,explode1,explode2,explode3,logo,mybullet,myexplode,myplane,preloader,replaybutton,share,sharebutton,startbutton}